kind: pipeline
type: docker
name: cms-api

steps:
  - name: build
    image: 192.168.0.124:5000/plugins/docker
    pull: if-not-exists
    settings:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      repo: ${REGISTRY_BASE}/ruanjiayou/cms-api
      tags: latest,${DRONE_COMMIT_SHA:0:7}
      build_args: 
        - NODE_ENV=production
    when:
      branch: main
      event: push