version: "3"
services: 
  manager-api:
    container_name: "manager-api"
    image: node:lts-alpine
    env_file:
      - .env
    working_dir: "/home/manager-api/"
    environment:
      mongo_system_url: mongodb://root:123456@mongo-demo:27017/schema?authSource=admin
      proxy_host: 127.0.0.1:3333
    networks: 
      - allinone
    volumes:
      - ./:/home/manager-api/
    ports:
      - "3333:3333"
    command: "npm start"
networks: 
  allinone:
    external: true